import Head from 'next/head'
import Image from 'next/image'
import Footer from '../Components/Footer'
import Navbar from '../Components/Navbar'
import Intro from '../Components/Intro'
import styles from '../styles/Home.module.css'
import Services from '../Components/Services'
import { data } from '../data'
import Testimonials from '../Components/Testimonials'

export default function Home({services}) {
  console.log(services);
  return (
    <div className={styles.container}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Intro />
      <Services services={services}/>
      <Testimonials />
    </div>
  )
}

export const getStaticProps =async ()=>{
  const services = data;
  return{props:{services}}
}